# Generated by Django 5.1.7 on 2025-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
