# Generated by Django 5.1.7 on 2025-03-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_item_photo_url_alter_item_category_alter_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo_url',
        ),
    ]
