# Generated by Django 5.1.7 on 2025-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_item_photo_url_alter_item_category_alter_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='structure',
            field=models.TextField(max_length=100),
        ),
    ]
