# Generated by Django 5.1.7 on 2025-03-27 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_item_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
