# Generated by Django 5.1.7 on 2025-03-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
