# Generated by Django 5.1.7 on 2025-03-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_item_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo_url',
        ),
    ]
